### ISSUE TITLE
Check Team Project 2 Submission

### ISSUE THREAD

**Issue by ChananM** [ChananM/AgudaJce#1]
#### Related Task
- [x] Open group repository
- [x] Meet up with the JCE Student Union
- [x] Write README File specified for the team project
- [x] Open User Manual page in wiki
- [x] Open Product page in wiki
- [x] Open Team page in wiki
- [x] Open Inception page in wiki
- [x] Collaborate repository with Eran and Reuven

**Comment by robi-y** [comment]
Excellent work, some comments:
- Readme: remove demo link, if it is not active yet
- Inception: risks are mostly team related, not client/product/technological/etc/
    - A use case diagram in not optimal for discussing software structure, better use deployment or even class diagrams

**Comment by ChananM** [comment]
@robi-y 
- Demo link was removed
- Multiple risks were added
- Use case diagram was changed to a general structure diagram
