### ISSUE TITLE
Install app modules - round 1

### ISSUE THREAD

**Issue by liorva** [ChananM/AgudaJce#4]
## Install extra node_modules
- Sync your local project with repository
- Open CMD, navigate to AgudaApp directory and run the commands (one by one):

```
npm install --save @ionic-native/fcm
npm install --save @ionic-native/firebase
npm install angularfire2 firebase promise-polyfill --save
```

#### Sign your checkbox here when you done.

- [x] @ChananM 
- [x] @odeliaevgi 
- [x] @danielifshitz 
- [x] @eliyahweinberg

**Comment by odeliaevgi** [comment]
finished

**Comment by danielifshitz** [comment]
finished
