### ISSUE TITLE
Install app modules - round 2

### ISSUE THREAD

**Issue by eliyahweinberg** [ChananM/AgudaJce#40]
## Install extra node_modules
- Sync your local project with repository
- Open CMD, navigate to AgudaApp directory and run the commands (one by one):

```
npm install --save @ionic-native/in-app-browser
npm install --save @ionic-native/calendar
npm install ionic-gallery-modal --save
```

- ### After installation go to firebase.app.module.d.ts
in node modules/angularfire 2 and make automatic correction - FirebaseApp should look like this:
```
export declare class FirebaseApp implements FBApp {
    automaticDataCollectionEnabled: boolean;

```

#### Sign your checkbox here when you done.

- [x] @ChananM 
- [x] @odeliaevgi 
- [x] @danielifshitz 
- [x] @liorva

**Comment by odeliaevgi** [comment]
closed
