### ISSUE TITLE
Install node modules - round 3

### ISSUE THREAD

**Issue by ChananM** [ChananM/AgudaJce#47]
## Install extra node_modules
- Sync your local project with repository
- Open CMD, navigate to AgudaApp directory and run the commands (one by one):

```
npm install ngx-quill-wrapper --save
```

#### Sign your checkbox here when you done.

- [x] @eliyahweinberg 
- [x] @odeliaevgi 
- [x] @danielifshitz 
- [x] @liorva

**Comment by odeliaevgi** [comment]
done
