### ISSUE TITLE
Information fixes

### ISSUE THREAD

**Issue by ChananM** [ChananM/AgudaJce#53]
Some minor fixes are needed for the information page:

1. Update the year in the contact page:
![image](https://user-images.githubusercontent.com/19833937/41020200-92a2f490-696a-11e8-9a23-9bd4c47217b2.png)

2. Update the FAQ page with the information you received from Lidor.

3. In the departments page:
- ![duplicate mails](https://placehold.it/15/f03c15/000000?text=+) delete the duplicate mails 
- ![#1589F0](https://placehold.it/15/1589F0/000000?text=+) move the office mail to the contact page

![image](https://user-images.githubusercontent.com/19833937/41020343-3165a0dc-696b-11e8-9b86-eade0e251916.png)

4. Add mail linking to each department page. for example:
![image](https://user-images.githubusercontent.com/19833937/41020672-70d36172-696c-11e8-9adb-18deadb59a9f.png)

**Comment by odeliaevgi** [comment]
fixed
