### ISSUE TITLE
Modify gallery page with ion-slide and ion-card

### ISSUE THREAD

**Issue by ChananM** [ChananM/AgudaJce#6]
Edit the gallery page to show a basic design of a grid with images of the organization

**Comment by liorva** [comment]
that's can help with the "Albums" view:
https://ionicframework.com/docs/components/#card-background

source:
https://github.com/ionic-team/ionic-preview-app/tree/master/src/pages/cards/background

**Comment by liorva** [comment]
@danielifshitz 
you can use this:
https://ionicacademy.com/ionic-image-gallery-responsive/
