### ISSUE TITLE
Integrate Facebook API to gallery page

### ISSUE THREAD

**Issue by ChananM** [ChananM/AgudaJce#8]
Integrate Facebook API to show images from the organization facebook page to the gallery page

Use case acceptence:
1. Enter the gallery page
2. Verify the list of albums matches the albums of the organization Facebook page
3. Enter any album
4. Verify all the pictures from this album appear as they appear on Facebook

**Comment by liorva** [comment]
@danielifshitz  nice work.

some notes:

in callAlbum function, you should only 'nav-push' to fbImagesPage and store the album in nav-param.
in page fbImages you need to send the request to api and to build the array of urls
move this api calls to fbImagesPage constructor, don't forget the 'loading-bloker' like in gallery constructor.

![image](https://user-images.githubusercontent.com/19833935/40541196-7900a5dc-6023-11e8-92b4-ff6d2b7e6837.png)

**Comment by ChananM** [comment]
Test results: SUCCESS
All images from Facebook appear on the gallery page properly and are interactable
